"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.create_location import CreateLocation
from openziti_edge_client.model.meta import Meta
globals()['CreateLocation'] = CreateLocation
globals()['Meta'] = Meta
from openziti_edge_client.model.create_envelope import CreateEnvelope


class TestCreateEnvelope(unittest.TestCase):
    """CreateEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEnvelope(self):
        """Test CreateEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
