"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_client
from openziti_edge_client.api.posture_checks_api import PostureChecksApi  # noqa: E501


class TestPostureChecksApi(unittest.TestCase):
    """PostureChecksApi unit test stubs"""

    def setUp(self):
        self.api = PostureChecksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_posture_response(self):
        """Test case for create_posture_response

        Submit a posture response to a posture query  # noqa: E501
        """
        pass

    def test_create_posture_response_bulk(self):
        """Test case for create_posture_response_bulk

        Submit multiple posture responses  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
