"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.authenticator_list import AuthenticatorList
from openziti_edge_client.model.meta import Meta
globals()['AuthenticatorList'] = AuthenticatorList
globals()['Meta'] = Meta
from openziti_edge_client.model.list_authenticators_envelope import ListAuthenticatorsEnvelope


class TestListAuthenticatorsEnvelope(unittest.TestCase):
    """ListAuthenticatorsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAuthenticatorsEnvelope(self):
        """Test ListAuthenticatorsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAuthenticatorsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
