"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.posture_check_type import PostureCheckType
from openziti_edge_client.model.posture_response_create import PostureResponseCreate
from openziti_edge_client.model.posture_response_domain_create_all_of import PostureResponseDomainCreateAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureResponseCreate'] = PostureResponseCreate
globals()['PostureResponseDomainCreateAllOf'] = PostureResponseDomainCreateAllOf
from openziti_edge_client.model.posture_response_domain_create import PostureResponseDomainCreate


class TestPostureResponseDomainCreate(unittest.TestCase):
    """PostureResponseDomainCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureResponseDomainCreate(self):
        """Test PostureResponseDomainCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureResponseDomainCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
