"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.client_external_jwt_signer_list import ClientExternalJwtSignerList
from openziti_edge_client.model.meta import Meta
globals()['ClientExternalJwtSignerList'] = ClientExternalJwtSignerList
globals()['Meta'] = Meta
from openziti_edge_client.model.list_client_external_jwt_signers_envelope import ListClientExternalJwtSignersEnvelope


class TestListClientExternalJwtSignersEnvelope(unittest.TestCase):
    """ListClientExternalJwtSignersEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListClientExternalJwtSignersEnvelope(self):
        """Test ListClientExternalJwtSignersEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListClientExternalJwtSignersEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
