"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.current_api_session_detail import CurrentApiSessionDetail
from openziti_edge_client.model.meta import Meta
globals()['CurrentApiSessionDetail'] = CurrentApiSessionDetail
globals()['Meta'] = Meta
from openziti_edge_client.model.current_api_session_detail_envelope import CurrentApiSessionDetailEnvelope


class TestCurrentApiSessionDetailEnvelope(unittest.TestCase):
    """CurrentApiSessionDetailEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrentApiSessionDetailEnvelope(self):
        """Test CurrentApiSessionDetailEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurrentApiSessionDetailEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
