"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.posture_check_type import PostureCheckType
from openziti_edge_client.model.posture_response_create import PostureResponseCreate
from openziti_edge_client.model.posture_response_process_create_all_of import PostureResponseProcessCreateAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureResponseCreate'] = PostureResponseCreate
globals()['PostureResponseProcessCreateAllOf'] = PostureResponseProcessCreateAllOf
from openziti_edge_client.model.posture_response_process_create import PostureResponseProcessCreate


class TestPostureResponseProcessCreate(unittest.TestCase):
    """PostureResponseProcessCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureResponseProcessCreate(self):
        """Test PostureResponseProcessCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureResponseProcessCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
