"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_client
from openziti_edge_client.api.well_known_api import WellKnownApi  # noqa: E501


class TestWellKnownApi(unittest.TestCase):
    """WellKnownApi unit test stubs"""

    def setUp(self):
        self.api = WellKnownApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_well_known_cas(self):
        """Test case for list_well_known_cas

        Get CA Cert Store  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
