"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.api_error import ApiError
from openziti_edge_client.model.meta import Meta
globals()['ApiError'] = ApiError
globals()['Meta'] = Meta
from openziti_edge_client.model.api_error_envelope import ApiErrorEnvelope


class TestApiErrorEnvelope(unittest.TestCase):
    """ApiErrorEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiErrorEnvelope(self):
        """Test ApiErrorEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiErrorEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
