"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.current_identity_edge_router_list import CurrentIdentityEdgeRouterList
from openziti_edge_client.model.meta import Meta
globals()['CurrentIdentityEdgeRouterList'] = CurrentIdentityEdgeRouterList
globals()['Meta'] = Meta
from openziti_edge_client.model.list_current_identity_edge_routers_envelope import ListCurrentIdentityEdgeRoutersEnvelope


class TestListCurrentIdentityEdgeRoutersEnvelope(unittest.TestCase):
    """ListCurrentIdentityEdgeRoutersEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCurrentIdentityEdgeRoutersEnvelope(self):
        """Test ListCurrentIdentityEdgeRoutersEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCurrentIdentityEdgeRoutersEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
