"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.entity_ref import EntityRef
globals()['EntityRef'] = EntityRef
from openziti_edge_client.model.terminator_client_detail_all_of import TerminatorClientDetailAllOf


class TestTerminatorClientDetailAllOf(unittest.TestCase):
    """TerminatorClientDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerminatorClientDetailAllOf(self):
        """Test TerminatorClientDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TerminatorClientDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
