"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.posture_check_type import PostureCheckType
from openziti_edge_client.model.posture_query_process import PostureQueryProcess
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureQueryProcess'] = PostureQueryProcess
from openziti_edge_client.model.posture_query_all_of import PostureQueryAllOf


class TestPostureQueryAllOf(unittest.TestCase):
    """PostureQueryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureQueryAllOf(self):
        """Test PostureQueryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureQueryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
