"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.posture_response import PostureResponse
globals()['Meta'] = Meta
globals()['PostureResponse'] = PostureResponse
from openziti_edge_client.model.posture_response_envelope import PostureResponseEnvelope


class TestPostureResponseEnvelope(unittest.TestCase):
    """PostureResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureResponseEnvelope(self):
        """Test PostureResponseEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureResponseEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
