"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.spec_list import SpecList
globals()['Meta'] = Meta
globals()['SpecList'] = SpecList
from openziti_edge_client.model.list_specs_envelope import ListSpecsEnvelope


class TestListSpecsEnvelope(unittest.TestCase):
    """ListSpecsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSpecsEnvelope(self):
        """Test ListSpecsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSpecsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
