"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_client
from openziti_edge_client.api.external_jwt_signer_api import ExternalJWTSignerApi  # noqa: E501


class TestExternalJWTSignerApi(unittest.TestCase):
    """ExternalJWTSignerApi unit test stubs"""

    def setUp(self):
        self.api = ExternalJWTSignerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_external_jwt_signers(self):
        """Test case for list_external_jwt_signers

        List Client Authentication External JWT  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
