"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.terminator_client_list import TerminatorClientList
globals()['Meta'] = Meta
globals()['TerminatorClientList'] = TerminatorClientList
from openziti_edge_client.model.list_client_terminators_envelope import ListClientTerminatorsEnvelope


class TestListClientTerminatorsEnvelope(unittest.TestCase):
    """ListClientTerminatorsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListClientTerminatorsEnvelope(self):
        """Test ListClientTerminatorsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListClientTerminatorsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
