"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.attributes import Attributes
from openziti_edge_client.model.base_entity import BaseEntity
from openziti_edge_client.model.dial_bind_array import DialBindArray
from openziti_edge_client.model.links import Links
from openziti_edge_client.model.posture_queries import PostureQueries
from openziti_edge_client.model.service_detail_all_of import ServiceDetailAllOf
from openziti_edge_client.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['BaseEntity'] = BaseEntity
globals()['DialBindArray'] = DialBindArray
globals()['Links'] = Links
globals()['PostureQueries'] = PostureQueries
globals()['ServiceDetailAllOf'] = ServiceDetailAllOf
globals()['Tags'] = Tags
from openziti_edge_client.model.service_detail import ServiceDetail


class TestServiceDetail(unittest.TestCase):
    """ServiceDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceDetail(self):
        """Test ServiceDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
