"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_client
from openziti_edge_client.api.edge_router_api import EdgeRouterApi  # noqa: E501


class TestEdgeRouterApi(unittest.TestCase):
    """EdgeRouterApi unit test stubs"""

    def setUp(self):
        self.api = EdgeRouterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_identity_edge_routers(self):
        """Test case for get_current_identity_edge_routers

        Return this list of Edge Routers the identity has access to  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
