"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.detail_mfa import DetailMfa
from openziti_edge_client.model.meta import Meta
globals()['DetailMfa'] = DetailMfa
globals()['Meta'] = Meta
from openziti_edge_client.model.detail_mfa_envelope import DetailMfaEnvelope


class TestDetailMfaEnvelope(unittest.TestCase):
    """DetailMfaEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailMfaEnvelope(self):
        """Test DetailMfaEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailMfaEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
