"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.base_entity import BaseEntity
from openziti_edge_client.model.entity_ref import EntityRef
from openziti_edge_client.model.links import Links
from openziti_edge_client.model.tags import Tags
from openziti_edge_client.model.terminator_client_detail_all_of import TerminatorClientDetailAllOf
globals()['BaseEntity'] = BaseEntity
globals()['EntityRef'] = EntityRef
globals()['Links'] = Links
globals()['Tags'] = Tags
globals()['TerminatorClientDetailAllOf'] = TerminatorClientDetailAllOf
from openziti_edge_client.model.terminator_client_detail import TerminatorClientDetail


class TestTerminatorClientDetail(unittest.TestCase):
    """TerminatorClientDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerminatorClientDetail(self):
        """Test TerminatorClientDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TerminatorClientDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
