"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.base_entity import BaseEntity
from openziti_edge_client.model.links import Links
from openziti_edge_client.model.spec_detail_all_of import SpecDetailAllOf
from openziti_edge_client.model.tags import Tags
globals()['BaseEntity'] = BaseEntity
globals()['Links'] = Links
globals()['SpecDetailAllOf'] = SpecDetailAllOf
globals()['Tags'] = Tags
from openziti_edge_client.model.spec_detail import SpecDetail


class TestSpecDetail(unittest.TestCase):
    """SpecDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecDetail(self):
        """Test SpecDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpecDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
