"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.api_error import ApiError
from openziti_edge_client.model.api_error_args import ApiErrorArgs
from openziti_edge_client.model.api_field_error import ApiFieldError
globals()['ApiError'] = ApiError
globals()['ApiErrorArgs'] = ApiErrorArgs
globals()['ApiFieldError'] = ApiFieldError
from openziti_edge_client.model.api_error_cause import ApiErrorCause


class TestApiErrorCause(unittest.TestCase):
    """ApiErrorCause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiErrorCause(self):
        """Test ApiErrorCause"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiErrorCause()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
