"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.attributes import Attributes


class TestAttributes(unittest.TestCase):
    """Attributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributes(self):
        """Test Attributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Attributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
