"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.links import Links
from openziti_edge_client.model.tags import Tags
globals()['Links'] = Links
globals()['Tags'] = Tags
from openziti_edge_client.model.base_entity import BaseEntity


class TestBaseEntity(unittest.TestCase):
    """BaseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseEntity(self):
        """Test BaseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
