"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.current_api_session_certificate_list import CurrentApiSessionCertificateList
from openziti_edge_client.model.meta import Meta
globals()['CurrentApiSessionCertificateList'] = CurrentApiSessionCertificateList
globals()['Meta'] = Meta
from openziti_edge_client.model.list_current_api_session_certificates_envelope import ListCurrentApiSessionCertificatesEnvelope


class TestListCurrentApiSessionCertificatesEnvelope(unittest.TestCase):
    """ListCurrentApiSessionCertificatesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCurrentApiSessionCertificatesEnvelope(self):
        """Test ListCurrentApiSessionCertificatesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCurrentApiSessionCertificatesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
