"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.client_external_jwt_signer_detail import ClientExternalJwtSignerDetail
globals()['ClientExternalJwtSignerDetail'] = ClientExternalJwtSignerDetail
from openziti_edge_client.model.client_external_jwt_signer_list import ClientExternalJwtSignerList


class TestClientExternalJwtSignerList(unittest.TestCase):
    """ClientExternalJwtSignerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientExternalJwtSignerList(self):
        """Test ClientExternalJwtSignerList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClientExternalJwtSignerList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
