"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.current_api_session_service_update_list import CurrentApiSessionServiceUpdateList
from openziti_edge_client.model.meta import Meta
globals()['CurrentApiSessionServiceUpdateList'] = CurrentApiSessionServiceUpdateList
globals()['Meta'] = Meta
from openziti_edge_client.model.list_current_api_session_service_updates_envelope import ListCurrentApiSessionServiceUpdatesEnvelope


class TestListCurrentApiSessionServiceUpdatesEnvelope(unittest.TestCase):
    """ListCurrentApiSessionServiceUpdatesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCurrentApiSessionServiceUpdatesEnvelope(self):
        """Test ListCurrentApiSessionServiceUpdatesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCurrentApiSessionServiceUpdatesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
