"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.current_api_session_certificate_create_response_all_of import CurrentApiSessionCertificateCreateResponseAllOf


class TestCurrentApiSessionCertificateCreateResponseAllOf(unittest.TestCase):
    """CurrentApiSessionCertificateCreateResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrentApiSessionCertificateCreateResponseAllOf(self):
        """Test CurrentApiSessionCertificateCreateResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurrentApiSessionCertificateCreateResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
