"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.dial_bind import DialBind
from openziti_edge_client.model.posture_query import PostureQuery
globals()['DialBind'] = DialBind
globals()['PostureQuery'] = PostureQuery
from openziti_edge_client.model.posture_queries import PostureQueries


class TestPostureQueries(unittest.TestCase):
    """PostureQueries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureQueries(self):
        """Test PostureQueries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureQueries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
