"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.spec_detail_all_of import SpecDetailAllOf


class TestSpecDetailAllOf(unittest.TestCase):
    """SpecDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecDetailAllOf(self):
        """Test SpecDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpecDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
