"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.common_edge_router_properties import CommonEdgeRouterProperties
from openziti_edge_client.model.session_edge_router_all_of import SessionEdgeRouterAllOf
from openziti_edge_client.model.tags import Tags
globals()['CommonEdgeRouterProperties'] = CommonEdgeRouterProperties
globals()['SessionEdgeRouterAllOf'] = SessionEdgeRouterAllOf
globals()['Tags'] = Tags
from openziti_edge_client.model.session_edge_router import SessionEdgeRouter


class TestSessionEdgeRouter(unittest.TestCase):
    """SessionEdgeRouter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionEdgeRouter(self):
        """Test SessionEdgeRouter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionEdgeRouter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
