"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.service_detail import ServiceDetail
globals()['Meta'] = Meta
globals()['ServiceDetail'] = ServiceDetail
from openziti_edge_client.model.detail_service_envelope import DetailServiceEnvelope


class TestDetailServiceEnvelope(unittest.TestCase):
    """DetailServiceEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailServiceEnvelope(self):
        """Test DetailServiceEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailServiceEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
