"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.authenticator_detail import AuthenticatorDetail
globals()['AuthenticatorDetail'] = AuthenticatorDetail
from openziti_edge_client.model.authenticator_list import AuthenticatorList


class TestAuthenticatorList(unittest.TestCase):
    """AuthenticatorList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticatorList(self):
        """Test AuthenticatorList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticatorList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
