"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.posture_check_type import PostureCheckType
from openziti_edge_client.model.posture_response_domain_create import PostureResponseDomainCreate
from openziti_edge_client.model.posture_response_endpoint_state_create import PostureResponseEndpointStateCreate
from openziti_edge_client.model.posture_response_mac_address_create import PostureResponseMacAddressCreate
from openziti_edge_client.model.posture_response_operating_system_create import PostureResponseOperatingSystemCreate
from openziti_edge_client.model.posture_response_process_create import PostureResponseProcessCreate
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureResponseDomainCreate'] = PostureResponseDomainCreate
globals()['PostureResponseEndpointStateCreate'] = PostureResponseEndpointStateCreate
globals()['PostureResponseMacAddressCreate'] = PostureResponseMacAddressCreate
globals()['PostureResponseOperatingSystemCreate'] = PostureResponseOperatingSystemCreate
globals()['PostureResponseProcessCreate'] = PostureResponseProcessCreate
from openziti_edge_client.model.posture_response_create import PostureResponseCreate


class TestPostureResponseCreate(unittest.TestCase):
    """PostureResponseCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureResponseCreate(self):
        """Test PostureResponseCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureResponseCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
