"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.spec_detail import SpecDetail
globals()['Meta'] = Meta
globals()['SpecDetail'] = SpecDetail
from openziti_edge_client.model.detail_spec_envelope import DetailSpecEnvelope


class TestDetailSpecEnvelope(unittest.TestCase):
    """DetailSpecEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailSpecEnvelope(self):
        """Test DetailSpecEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailSpecEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
