"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.api_session_detail import ApiSessionDetail
from openziti_edge_client.model.auth_query_list import AuthQueryList
from openziti_edge_client.model.current_api_session_detail_all_of import CurrentApiSessionDetailAllOf
from openziti_edge_client.model.entity_ref import EntityRef
from openziti_edge_client.model.links import Links
from openziti_edge_client.model.tags import Tags
globals()['ApiSessionDetail'] = ApiSessionDetail
globals()['AuthQueryList'] = AuthQueryList
globals()['CurrentApiSessionDetailAllOf'] = CurrentApiSessionDetailAllOf
globals()['EntityRef'] = EntityRef
globals()['Links'] = Links
globals()['Tags'] = Tags
from openziti_edge_client.model.current_api_session_detail import CurrentApiSessionDetail


class TestCurrentApiSessionDetail(unittest.TestCase):
    """CurrentApiSessionDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrentApiSessionDetail(self):
        """Test CurrentApiSessionDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurrentApiSessionDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
