"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.pagination import Pagination
globals()['Pagination'] = Pagination
from openziti_edge_client.model.meta import Meta


class TestMeta(unittest.TestCase):
    """Meta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeta(self):
        """Test Meta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Meta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
