"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.service_list import ServiceList
globals()['Meta'] = Meta
globals()['ServiceList'] = ServiceList
from openziti_edge_client.model.list_services_envelope import ListServicesEnvelope


class TestListServicesEnvelope(unittest.TestCase):
    """ListServicesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListServicesEnvelope(self):
        """Test ListServicesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListServicesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
