"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.session_detail import SessionDetail
globals()['Meta'] = Meta
globals()['SessionDetail'] = SessionDetail
from openziti_edge_client.model.detail_session_envelope import DetailSessionEnvelope


class TestDetailSessionEnvelope(unittest.TestCase):
    """DetailSessionEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailSessionEnvelope(self):
        """Test DetailSessionEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailSessionEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
