"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.current_api_session_certificate_create_response import CurrentApiSessionCertificateCreateResponse
from openziti_edge_client.model.meta import Meta
globals()['CurrentApiSessionCertificateCreateResponse'] = CurrentApiSessionCertificateCreateResponse
globals()['Meta'] = Meta
from openziti_edge_client.model.create_current_api_session_certificate_envelope import CreateCurrentApiSessionCertificateEnvelope


class TestCreateCurrentApiSessionCertificateEnvelope(unittest.TestCase):
    """CreateCurrentApiSessionCertificateEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCurrentApiSessionCertificateEnvelope(self):
        """Test CreateCurrentApiSessionCertificateEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCurrentApiSessionCertificateEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
