"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.terminator_precedence import TerminatorPrecedence


class TestTerminatorPrecedence(unittest.TestCase):
    """TerminatorPrecedence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerminatorPrecedence(self):
        """Test TerminatorPrecedence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TerminatorPrecedence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
