"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.meta import Meta
from openziti_edge_client.model.session_list import SessionList
globals()['Meta'] = Meta
globals()['SessionList'] = SessionList
from openziti_edge_client.model.list_sessions_envelope import ListSessionsEnvelope


class TestListSessionsEnvelope(unittest.TestCase):
    """ListSessionsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSessionsEnvelope(self):
        """Test ListSessionsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSessionsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
