"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_client
from openziti_edge_client.api.current_api_session_api import CurrentAPISessionApi  # noqa: E501


class TestCurrentAPISessionApi(unittest.TestCase):
    """CurrentAPISessionApi unit test stubs"""

    def setUp(self):
        self.api = CurrentAPISessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_current_api_session_certificate(self):
        """Test case for create_current_api_session_certificate

        Creates an ephemeral certificate for the current API Session  # noqa: E501
        """
        pass

    def test_current_api_session_delete(self):
        """Test case for current_api_session_delete

        Logout  # noqa: E501
        """
        pass

    def test_delete_current_api_session_certificate(self):
        """Test case for delete_current_api_session_certificate

        Delete an ephemeral certificate  # noqa: E501
        """
        pass

    def test_detail_current_api_session_certificate(self):
        """Test case for detail_current_api_session_certificate

        Retrieves an ephemeral certificate  # noqa: E501
        """
        pass

    def test_detail_current_identity_authenticator(self):
        """Test case for detail_current_identity_authenticator

        Retrieve an authenticator for the current identity  # noqa: E501
        """
        pass

    def test_extend_current_identity_authenticator(self):
        """Test case for extend_current_identity_authenticator

        Allows the current identity to recieve a new certificate associated with a certificate based authenticator  # noqa: E501
        """
        pass

    def test_extend_verify_current_identity_authenticator(self):
        """Test case for extend_verify_current_identity_authenticator

        Allows the current identity to validate reciept of a new client certificate  # noqa: E501
        """
        pass

    def test_get_current_api_session(self):
        """Test case for get_current_api_session

        Return the current API session  # noqa: E501
        """
        pass

    def test_list_current_api_session_certificates(self):
        """Test case for list_current_api_session_certificates

        List the ephemeral certificates available for the current API Session  # noqa: E501
        """
        pass

    def test_list_current_identity_authenticators(self):
        """Test case for list_current_identity_authenticators

        List authenticators for the current identity  # noqa: E501
        """
        pass

    def test_list_service_updates(self):
        """Test case for list_service_updates

        Returns data indicating whether a client should updates it service list  # noqa: E501
        """
        pass

    def test_patch_current_identity_authenticator(self):
        """Test case for patch_current_identity_authenticator

        Update the supplied fields on an authenticator of this identity  # noqa: E501
        """
        pass

    def test_update_current_identity_authenticator(self):
        """Test case for update_current_identity_authenticator

        Update all fields on an authenticator of this identity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
