"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.identity_detail import IdentityDetail
from openziti_edge_client.model.meta import Meta
globals()['IdentityDetail'] = IdentityDetail
globals()['Meta'] = Meta
from openziti_edge_client.model.current_identity_detail_envelope import CurrentIdentityDetailEnvelope


class TestCurrentIdentityDetailEnvelope(unittest.TestCase):
    """CurrentIdentityDetailEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrentIdentityDetailEnvelope(self):
        """Test CurrentIdentityDetailEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurrentIdentityDetailEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
