"""
    Ziti Edge Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_client
from openziti_edge_client.model.authenticator_patch import AuthenticatorPatch
from openziti_edge_client.model.authenticator_patch_with_current_all_of import AuthenticatorPatchWithCurrentAllOf
from openziti_edge_client.model.password import Password
from openziti_edge_client.model.password_nullable import PasswordNullable
from openziti_edge_client.model.tags import Tags
from openziti_edge_client.model.username_nullable import UsernameNullable
globals()['AuthenticatorPatch'] = AuthenticatorPatch
globals()['AuthenticatorPatchWithCurrentAllOf'] = AuthenticatorPatchWithCurrentAllOf
globals()['Password'] = Password
globals()['PasswordNullable'] = PasswordNullable
globals()['Tags'] = Tags
globals()['UsernameNullable'] = UsernameNullable
from openziti_edge_client.model.authenticator_patch_with_current import AuthenticatorPatchWithCurrent


class TestAuthenticatorPatchWithCurrent(unittest.TestCase):
    """AuthenticatorPatchWithCurrent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticatorPatchWithCurrent(self):
        """Test AuthenticatorPatchWithCurrent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticatorPatchWithCurrent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
